### ISSUE TITLE
Usage Error of validator, field, config, and info in Pydantic V2 when running test_reflexion.sh

### ISSUE THREAD

**Issue by ziyuwan** [mail-ecnu/Text-Gym-Agents#2]
Hi, I'm trying to run the testing scripts of `test_reflexion.sh` and I got the following error:
```
llm-gym/lib/python3.8/site-packages/pydantic/_internal/_decorators_v1.py", line 77, in make_generic_v1_field_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: The `field` and `config` parameters are not available in Pydantic V2, please use the `info` parameter instead.
```
And on the [doc of pydantic](https://docs.pydantic.dev/2.3/errors/usage_errors/#validator-field-config-info), there is also some description about the usage errors in Version 2:

> The `field` argument is no longer available.

This indicates that in Pydantic V2 there are no longer `field` parameter, which is used in the code like [here](https://github.com/mail-ecnu/Text-Gym-Agents/blob/22f063c7e399f7ec5d9e089a3302108cef9f423a/deciders/parser.py#L9C12-L9C12)

however, when I check the `environment.yml` again, I find the required version is `pydantic==2.3.0, pydantic-core==2.6.3` and I've got the above PydanticUserError with the required versions.

Therefore, is there any mistakes I've made during the environment setup or should I change the version of `pydantic` to V1?

**Comment by ziyuwan** [comment]
I've found an official code transformation tool [here](https://docs.pydantic.dev/latest/migration/#code-transformation-tool), which is helpful for migration from v1 to v2

**Comment by hzxwonder** [comment]
Hello, sorry about that, the new environment.yaml has fixed the problem by downgrading the version of pydantic to 1.10.11 at PR#3

**Comment by ziyuwan** [comment]
ok, thanks for your help! I'll close this issue
